MvcMovie/Models/Class.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace MvcMovie.Models
{
    public class Movie : IValidatableObject
    {
        public int Id { get; set; }

        public string Title { get; set; }

        [Display(Name = "ReleaseDate", Prompt = "Release5Date")]
        [DisplayName("ReleaseDate")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        public string Rating { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            return null;
        }
    }
}

MvcMovie/Models/ErrorViewModel.cs
using System;

namespace MvcMovie.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcMovie/Models/Movie.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcMovie.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}

MvcMovie/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using Service;
using Model;
using Utility.Operator;
using Microsoft.Extensions.Logging;
using log4net;
using Blog.Core.Log;
using System;
using Microsoft.Extensions.Localization;


namespace MvcMovie.Controllers
{
    public class HelloWorldController : Controller
    {
        private readonly IStringLocalizer<HelloWorldController> _localizer;

    

        // 
        // GET: /HelloWorld/
        private readonly IUseRBLL _UseRBLL;
        private readonly ILoggerHelper _log;
        public HelloWorldController(IUseRBLL UseRBLL, ILoggerHelper log,IStringLocalizer<HelloWorldController> localizer)
        {
            _UseRBLL = UseRBLL;
           _log = log;
            _localizer = localizer;
        }
        public string Index()
        {

            return "This is my default action...";
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public string Welcome()
        {
            return "This is the Welcome action method...";
        }


        public IActionResult List()
        {
            new MovieServer().GetDb().GetById(12);
            return View();
        }
       public  IActionResult Insert()
        {
            ViewBag.data= _UseRBLL.testc() +
             _localizer["Hello world!"]; 
            return View();
        }
    }
}

MvcMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using log4net;
using log4net.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    [PermissionFilter]
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult SetCooke()
        {
            return Content("2222");
        }

        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            ILoggerRepository repository = LogManager.CreateRepository("NETCoreRepository");
            ILog log = LogManager.GetLogger(repository.Name, "NETCorelog4net");

            log.Info("NETCorelog4net log");
            log.Info("test log");
            log.Error("error");
            log.Info("linezero");
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcMovie/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Model;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcMovie.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Login(string returnUrl = "")
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost, ActionName("Login")]
        public async Task<IActionResult> LoginPost(LoginViewModel model, string returnUrl = "")
        {
            ViewData["ReturnUrl"] = returnUrl;
            ValidationAttributeUtil.GetRequiredErrorMessage("姓名");
            if (ModelState.IsValid)
            {
                bool succee = (model.UserName == "admin") && (model.Password == "123");

                if (succee)
                {
                    //创建用户身份标识
                    var claimsIdentity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                    claimsIdentity.AddClaims(new List<Claim>()
                    {
                        new Claim(ClaimTypes.Sid, model.UserName),
                        new Claim(ClaimTypes.Name, model.UserName),
                        new Claim(ClaimTypes.Role, "admin"),
                        new Claim("LastUpdated", "admin")//当密码有改动时
                    });

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return Content("ok");
                }
                else
                {
                    ModelState.AddModelError("ValidError", "帐号或者密码错误。");
                    StringBuilder strBuild = new StringBuilder();
                    foreach (var item in ModelState.Values)
                    {
                        if (item.Errors.Count > 0)
                        {
                            int itemErrorCount = item.Errors.Count;
                            for (int i = 0; i < itemErrorCount; i++)
                            {
                                strBuild.Append(item.Errors[i].ErrorMessage);
                                strBuild.Append("<br/>");
                            }
                        }
                    }
                  
                    return Json(strBuild.ToString());
                }
            }

            return Json(ModelState);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return Redirect("/Home/Index");
        }
    }
}

MvcMovie/Views/HelloWorld/Insert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
@ViewBag.data

MvcMovie/Views/HelloWorld/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

MvcMovie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="javascript:;" onclick="setpost()">building Web apps with ASP.NET Core</a>.</p>
</div>
<script>
    function setpost() {
        $.post("/home/SetCooke", "", function (data) {
            console.info(data);
        });
    }

</script>

MvcMovie/Views/Login/Login.cshtml
@model Model.LoginViewModel

@{
    ViewData["Title"] = "登录";
}
<style>
    /* ----- Validation and error messages class starts -----*/
    .input-validation-error {
        border-color: #dc3545;
    }

    /* -- --Validation and error messages class ends -- --*/
</style>
<div class="row">
    <div class="col-xs-10 col-sm-8 col-md-6">

        <form asp-controller="Login" asp-action="Login" formnovalidate
              data-ajax-begin="onBegin" data-ajax-complete="onComplete"
              data-ajax-failure="onFailed" data-ajax-success="onSuccess"
              data-ajax="true" data-ajax-method="POST" data-ajax-loading="#load">
            <!--所有的错误-->
            @*<div asp-validation-summary="All" class="text-danger"></div>*@
            <!---不包含属性上的错误---->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" placeholder="请输入用户名" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>

            </div>
            @*<field cols="3" label="wu">

            </field>

            <easyuivalidatebox asp-for="Password"    class="form-control" />

            <input asp-for="PUIuu" class="form-control " data-/>*@

            <button type="submit" class="btn btn-primary">登录</button>
        </form>
    </div>
</div>
<div id="Results"></div>

@section Scripts {

    <script>

        //创建简单遮罩层，显示load时的信息，配合Unobtrusive


        $(document).ready(function () {

            console.info($("div[data-loadlayer=true]"));
        });

        var results = $("#Results");
        var onBegin = function () {
            results.html("<img src=\"/images/ajax-loader.gif\" alt=\"Loading\" />");
        };

        var onComplete = function () {
            //results.html("");
        };

        var onSuccess = function (context) {
            alert(context);
        };

        var onFailed = function (context) {
            alert("Failed");
        };
    </script>
    <script>
        ; (function ($) {
            //设置背景层高
            function height() {
                var scrollHeight, offsetHeight;
                // handle IE 6
                if ($.browser.msie && $.browser.version < 7) {
                    scrollHeight = Math.max(document.documentElement.scrollHeight, document.body.scrollHeight);
                    offsetHeight = Math.max(document.documentElement.offsetHeight, document.body.offsetHeight);
                    if (scrollHeight < offsetHeight) {
                        return $(window).height();
                    } else {
                        return scrollHeight;
                    }
                    // handle "good" browsers
                }
                else if ($.browser.msie && $.browser.version == 8) {
                    return $(document).height() - 4;
                }
                else {
                    return $(document).height();
                }
            };
            //设置背景层宽
            function width() {
                var scrollWidth, offsetWidth;
                // handle IE
                if ($.browser.msie) {
                    scrollWidth = Math.max(document.documentElement.scrollWidth, document.body.scrollWidth);
                    offsetWidth = Math.max(document.documentElement.offsetWidth, document.body.offsetWidth);
                    if (scrollWidth < offsetWidth) {
                        return $(window).width();
                    } else {
                        return scrollWidth;
                    }
                    // handle "good" browsers
                }
                else {
                    return $(document).width();
                }
            };
            /*==========全部遮罩=========*/
            function createLayer(load) {
                //背景遮罩层
                var layer = $("<div id=" + load.attr("data-loadlayer-id") + "></div>");
                layer.css({
                    zIndex: 9998,
                    position: "absolute",
                    height: height() + "px",
                    width: width() + "px",
                    background: "black",
                    top: 0,
                    left: 0,
                    filter: "alpha(opacity=30)",
                    opacity: 0.3
                });

                //图片及文字层
                var content = $("<div id=" + load.attr("data-loadlayer-id") + "-content" + "></div>");
                content.css({
                    textAlign: "left",
                    position: "absolute",
                    zIndex: 9999,
                    //height: opt.height + "px",
                    //width: opt.width + "px",
                    top: "50%",
                    left: "50%",
                    verticalAlign: "middle",
                    //background: opt.backgroudColor,"#ECECEC"
                    background: "#ECECEC",
                    borderRadius: "3px",
                    padding: "2px 5px 2px 5px",
                    fontSize: "13px"
                });

                //content.append("<img style='vertical-align:middle;margin:" + (opt.height / 4) + "px; 0 0 5px;margin-right:5px;' src='" + opt.backgroundImage + "' /><span style='text-align:center; vertical-align:middle;'>" + opt.text + "</span>");
                content.append("<span style='text-align:center; vertical-align:middle;color:#000000'>" + load.attr("data-loadlayer-msg") + "</span>");
                load.append(layer.append(content));
                var top = content.css("top").replace('px', '');
                var left = content.css("left").replace('px', '');
                content.css("top", (parseFloat(top) - parseFloat(content.css("height")) / 2)).css("left", (parseFloat(left) - parseFloat(content.css("width")) / 2));
                console.info("backgroudColor");
                layer.hide();
                return this;
            }

            $(document).ready(function () {
                createLayer($("div[data-loadlayer=true]"))
                console.info("div[data-loadlayer=true]");
            });
        })($)
    </script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
}
<style>
    .loadEffect {
        width: 100px;
        height: 100px;
        position: relative;
        margin: 0 auto;
        margin-top: 100px;
    }

        .loadEffect span {
            display: inline-block;
            width: 16px;
            height: 16px;
            border-radius: 50%;
            background: lightgreen;
            position: absolute;
            -webkit-animation: load 1.04s ease infinite;
        }

    @@-webkit-keyframes load {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0.2;
        }
    }

    .loadEffect span:nth-child(1) {
        left: 0;
        top: 50%;
        margin-top: -8px;
        -webkit-animation-delay: 0.13s;
    }

    .loadEffect span:nth-child(2) {
        left: 14px;
        top: 14px;
        -webkit-animation-delay: 0.26s;
    }

    .loadEffect span:nth-child(3) {
        left: 50%;
        top: 0;
        margin-left: -8px;
        -webkit-animation-delay: 0.39s;
    }

    .loadEffect span:nth-child(4) {
        top: 14px;
        right: 14px;
        -webkit-animation-delay: 0.52s;
    }

    .loadEffect span:nth-child(5) {
        right: 0;
        top: 50%;
        margin-top: -8px;
        -webkit-animation-delay: 0.65s;
    }

    .loadEffect span:nth-child(6) {
        right: 14px;
        bottom: 14px;
        -webkit-animation-delay: 0.78s;
    }

    .loadEffect span:nth-child(7) {
        bottom: 0;
        left: 50%;
        margin-left: -8px;
        -webkit-animation-delay: 0.91s;
    }

    .loadEffect span:nth-child(8) {
        bottom: 14px;
        left: 14px;
        -webkit-animation-delay: 1.04s;
    }
</style>

@*<div class="loadEffect" id="loadEffect">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span class="">加载中</span>
    </div>*@

<div data-loadlayer="true" data-loadlayer-id="load" data-loadlayer-msg="loading..."></div>

<style>
    .datagrid-mask {
        background: #ccc;
    }

    .datagrid-mask-msg {
        border-color: #D3D3D3;
    }

    .datagrid-mask {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        opacity: 0.3;
        filter: alpha(opacity=30);
        display: none;
    }

    .datagrid-mask-msg {
        position: absolute;
        top: 50%;
        margin-top: -20px;
        padding: 10px 5px 10px 30px;
        width: auto;
        border-width: 2px;
        border-style: solid;
        display: none;
        background: #ffffff url('http://localhost:2323/Content/jquery-easyui-1.4.1/themes/gray/images/loading.gif') no-repeat scroll 5px center;
    }
</style>

<div id="loading" style="display:none">
    <div id="loading1" class="datagrid-mask" style="display: block; width: 100%; height: 937px; z-index: 10000;"></div>
    <div id="loading2" class="datagrid-mask-msg" style="display: block; left: 865px; top: 446px; z-index: 10000;">正在处理，请稍候。。。</div>
</div>

MvcMovie/Views/MovieMana/Insert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MvcMovie.Models.Movie
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<p>@Localizer["Hello world!"]</p>
<form action="/" method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input type="text" name="Title" value="" />
    </div>
    <div class="form-group">
        <label asp-for="ReleaseDate"></label>
        <input type="text" asp-for="ReleaseDate" value="" />
    </div>
</form>

MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMovie</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Insert">Insert</a>
                        </li>
                       
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>